name: fconsole
description: A overlay console log list like v-console.
version: 2.3.1
homepage: https://github.com/fluttercandies/fconsole

environment:
    sdk: ">=2.12.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    device_info_plus: ^8.0.0
    intl: ^0.17.0
    tapped: ^2.0.0
    animations: ^2.0.0
    left_scroll_actions: ^2.0.0
    share_plus: ^6.3.1
    json_view: ^0.4.0

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
